line_colors = [
    "#396ab1",
    "#da7c30",
    "#3e9651",
    "#cc2529",
    "#535154",
    "#6b4c9a",
    "#932428",
    "#948b3d",
]
bar_colors = [
    "#7293cb",
    "#e0974c",
    "#84ba5b",
    "#d25e60",
    "#7f8585",
    "#9067a7",
    "#ab6857",
    "#ccc210",
]

#color                     : #RGB
color_hex_codes = {
    'black':'#000000',
    'white':'#ffffff',
    'red':'#ff0000',
    'green':'#00ff00',
    'blue':'#0000ff',
    'cyan':'#00ffff',
    'magenta':'#ff00ff',
    'yellow':'#ffff00',
    'purple':'#6600cc',
    'dull-blue':'#0099ff',
    'dark-green-blue':'#33cccc',
    'medium-green-blue':'#00ffcc',
    'bright-blue':'#0033ff',
    'dark-green':'#009900',
    'bright-green':'#33cc00',
    'orange':'#ff3333',
    'orange-brown':'#cc6600',
    'brown':'#8b4513',
    'bright-red':'#cc0000',
    'light-gray':'#999999',
    'dark-gray':'#666666',
    'gray0':'#ffffff',
    'gray1':'#eeeeee',
    'gray2':'#dddddd',
    'gray3':'#cccccc',
    'gray4':'#bbbbbb',
    'gray5':'#aaaaaa',
    'gray6':'#999999',
    'gray7':'#888888',
    'gray8':'#777777',
    'gray9':'#666666',
    'gray10':'#555555',
    'gray11':'#444444',
    'gray12':'#333333',
    'gray13':'#222222',
    'gray14':'#111111',
    'gray15':'#000000',
    'clustal-red':'#e53319',
    'clustal-blue':'#197fe5',
    'clustal-green':'#19cc19',
    'clustal-cyan':'#19b2b2',
    'clustal-pink':'#e57f7f',
    'clustal-magenta':'#cc4ccc',
    'clustal-yellow':'#cccc00',
    'clustal-orange':'#e5994c',
    'clustal-white':'#ffffff',
    'clustal-light-gray':'#999999',
    'clustal-dark-gray':'#666666',
    'clustal-black':'#000000',
    'clustal-white-print':'#ffffff',
    'clustal-yellow-print':'#ffff00',
    'clustal-violet-print':'#6619e5',
    'clustal-red-print':'#e57f66',
    'clustal-blue-print':'#66e5e5',
    'clustal-purple-print':'#b299e5',
    'clustal-black-print':'#000000',
    'clustal-pink-print':'#e57f7f',
    'clustal-cyan-print':'#19b2b2',
    'clustal-magenta-print':'#cc4ccc',
    'clustal-orange-print':'#e5994c',
    'clustal-green-print':'#19cc19',
    'clustal-light-gray-print':'#999999',
    'clustal-dark-gray-print':'#99b2b2',
    'nardi-red':'#ff1111',
    'nardi-blue':'#1155ff',
    'nardi-green':'#11dd11',
    'nardi-cyan':'#11ffff',
    'nardi-yellow':'#ffff11',
    'nardi-orange':'#ff7f11',
    'nardi-pink':'#ff11ff',
    'nardi-purple':'#6611cc',
    'nardi-dull-blue':'#197fe5',
    'nardi-light-gray':'#999999',
    'nardi-dark-gray':'#666666',
    'lin-a':'#90fe23',
    'lin-r':'#fe5e2d',
    'lin-n':'#2e3d2d',
    'lin-d':'#00903b',
    'lin-c':'#004baa',
    'lin-q':'#864b00',
    'lin-e':'#3fa201',
    'lin-g':'#10fe68',
    'lin-h':'#b2063b',
    'lin-i':'#04ced9',
    'lin-l':'#4972fe',
    'lin-k':'#c4a100',
    'lin-m':'#2a84dd',
    'lin-f':'#a60ade',
    'lin-p':'#fe61fe',
    'lin-s':'#f7e847',
    'lin-t':'#fefeb3',
    'lin-w':'#4a007f',
    'lin-y':'#e903a8',
    'lin-v':'#5bfdfd',
    'find-a':'#90fe23',
    'find-b':'#fe5e2d',
    'find-c':'#2e3d2d',
    'find-d':'#00903b',
    'find-e':'#004baa',
    'find-f':'#864b00',
    'find-g':'#3fa201',
    'find-h':'#10fe68',
    'find-i':'#b2063b',
    'find-j':'#04ced9',
    'find-k':'#4972fe',
    'find-l':'#c4a100',
    'find-m':'#2a84dd',
    'find-n':'#a60ade',
    'find-o':'#fe61fe',
    'find-p':'#f7e847',
    'find-q':'#fefeb3',
    'find-r':'#4a007f',
    'find-s':'#e903a8',
    'find-t':'#5bfdfd',
    'silver':'#c0c0c0',
    'gray':'#808080',
    'maroon':'#800000',
    'olive':'#808000',
    'lime':'#00ff00',
    'aqua':'#00ffff',
    'teal':'#008080',
    'navy':'#000080',
    'fuchsia':'#ff00ff',
    'pink':'#ffc0cb',
    'lightpink':'#ffb6c1',
    'hotpink':'#ff69b4',
    'deeppink':'#ff1493',
    'palevioletred':'#db7093',
    'mediumvioletred':'#c71585',
    'lightsalmon':'#ffa07a',
    'salmon':'#fa8072',
    'darksalmon':'#e9967a',
    'lightcoral':'#f08080',
    'indianred':'#cd5c5c',
    'crimson':'#dc143c',
    'firebrick':'#b22222',
    'darkred':'#8b0000',
    'orangered':'#ff4500',
    'tomato':'#ff6347',
    'coral':'#ff7f50',
    'darkorange':'#ff8c00',
    'lightyellow':'#ffffe0',
    'lemonchiffon':'#fffacd',
    'lightgoldenrodyellow':'#fafad2',
    'papayawhip':'#ffefd5',
    'moccasin':'#ffe4b5',
    'peachpuff':'#ffdab9',
    'palegoldenrod':'#eee8aa',
    'khaki':'#f0e68c',
    'darkkhaki':'#bdb76b',
    'gold':'#ffd700',
    'cornsilk':'#fff8dc',
    'blanchedalmond':'#ffebcd',
    'bisque':'#ffe4c4',
    'navajowhite':'#ffdead',
    'wheat':'#f5deb3',
    'burlywood':'#deb887',
    'tan':'#d2b48c',
    'rosybrown':'#bc8f8f',
    'sandybrown':'#f4a460',
    'goldenrod':'#daa520',
    'darkgoldenrod':'#b8860b',
    'peru':'#cd853f',
    'chocolate':'#d2691e',
    'saddlebrown':'#8b4513',
    'sienna':'#a0522d',
    'darkolivegreen':'#556b2f',
    'olivedrab':'#6b8e23',
    'yellowgreen':'#9acd32',
    'limegreen':'#32cd32',
    'lawngreen':'#7cfc00',
    'chartreuse':'#7fff00',
    'greenyellow':'#adff2f',
    'springgreen':'#00ff7f',
    'mediumspringgreen':'#00fa9a',
    'lightgreen':'#90ee90',
    'palegreen':'#98fb98',
    'darkseagreen':'#8fbc8f',
    'mediumaquamarine':'#66cdaa',
    'mediumseagreen':'#3cb371',
    'seagreen':'#2e8b57',
    'forestgreen':'#228b22',
    'darkgreen':'#006400',
    'lightcyan':'#e0ffff',
    'paleturquoise':'#afeeee',
    'aquamarine':'#7fffd4',
    'turquoise':'#40e0d0',
    'mediumturquoise':'#48d1cc',
    'darkturquoise':'#00ced1',
    'lightseagreen':'#20b2aa',
    'cadetblue':'#5f9ea0',
    'darkcyan':'#008b8b',
    'lightsteelblue':'#b0c4de',
    'powderblue':'#b0e0e6',
    'lightblue':'#add8e6',
    'skyblue':'#87ceeb',
    'lightskyblue':'#87cefa',
    'deepskyblue':'#00bfff',
    'dodgerblue':'#1e90ff',
    'cornflowerblue':'#6495ed',
    'steelblue':'#4682b4',
    'royalblue':'#4169e1',
    'mediumblue':'#0000cd',
    'darkblue':'#00008b',
    'midnightblue':'#191970',
    'lavender':'#e6e6fa',
    'thistle':'#d8bfd8',
    'plum':'#dda0dd',
    'violet':'#ee82ee',
    'orchid':'#da70d6',
    'mediumorchid':'#ba55d3',
    'mediumpurple':'#9370db',
    'blueviolet':'#8a2be2',
    'darkviolet':'#9400d3',
    'darkorchid':'#9932cc',
    'darkmagenta':'#8b008b',
    'indigo':'#4b0082',
    'darkslateblue':'#483d8b',
    'slateblue':'#6a5acd',
    'mediumslateblue':'#7b68ee',
    'snow':'#fffafa',
    'honeydew':'#f0fff0',
    'mintcream':'#f5fffa',
    'azure':'#f0ffff',
    'aliceblue':'#f0f8ff',
    'ghostwhite':'#f8f8ff',
    'whitesmoke':'#f5f5f5',
    'seashell':'#fff5ee',
    'beige':'#f5f5dc',
    'oldlace':'#fdf5e6',
    'floralwhite':'#fffaf0',
    'ivory':'#fffff0',
    'antiquewhite':'#faebd7',
    'linen':'#faf0e6',
    'lavenderblush':'#fff0f5',
    'mistyrose':'#ffe4e1',
    'gainsboro':'#dcdcdc',
    'lightgray':'#d3d3d3',
    'darkgray':'#a9a9a9',
    'dimgray':'#696969',
    'lightslategray':'#778899',
    'slategray':'#708090',
    'darkslategray':'#2f4f4f',
}

color_maps = {
    'clustal': {
        '*':'black',
        '-':'black',
        '.':'clustal-dark-gray',
        '?':'clustal-light-gray',
        'A':'clustal-blue',
        'B':'clustal-white',
        'C':'clustal-pink',
        'D':'clustal-magenta',
        'E':'clustal-magenta',
        'F':'clustal-blue',
        'G':'clustal-orange',
        'H':'clustal-cyan',
        'I':'clustal-blue',
        'K':'clustal-red',
        'L':'clustal-blue',
        'M':'clustal-blue',
        'N':'clustal-green',
        'P':'clustal-yellow',
        'Q':'clustal-green',
        'R':'clustal-red',
        'S':'clustal-green',
        'T':'clustal-green',
        'V':'clustal-blue',
        'W':'clustal-blue',
        'X':'clustal-dark-gray',
        'Y':'clustal-cyan',
        'Z':'clustal-white',
    }
} 

def load_colormap(pallette='clustal'):
    '''load the clustal colormap as {'residue symbol':'hex color'}'''
    # cmap = {}
    # for key,value in color_maps['clustal'].items():
        # cmap[key] = color_hex_codes[value]
    return {key:color_hex_codes[value] for key,value in color_maps[pallette].items()}



# #Protein: highlight amino acid physicochemical properties
# #symbols =>  color                #comment
# *        =>  black                #stop
# .        =>  clustal-dark-gray    #wildcard/mismatch
# ?        =>  clustal-light-gray   #unknown
# Aa       =>  clustal-blue         #hydrophobic
# Bb       =>  clustal-white        #D or N
# Cc       =>  clustal-pink         #hydrophobic
# Dd       =>  clustal-magenta      #negative charge
# Ee       =>  clustal-magenta      #negative charge
# Ff       =>  clustal-blue         #large hydrophobic
# Gg       =>  clustal-orange       #glycine
# Hh       =>  clustal-cyan         #large hydrophobic
# Ii       =>  clustal-blue         #hydrophobic
# Kk       =>  clustal-red          #positive charge
# Ll       =>  clustal-blue         #hydrophobic
# Mm       =>  clustal-blue         #hydrophobic
# Nn       =>  clustal-green        #polar
# Pp       =>  clustal-yellow       #proline
# Qq       =>  clustal-green        #polar
# Rr       =>  clustal-red          #positive charge
# Ss       =>  clustal-green        #small alcohol
# Tt       =>  clustal-green        #small alcohol
# Vv       =>  clustal-blue         #hydrophobic
# Ww       =>  clustal-blue         #large hydrophobic
# Xx       =>  clustal-dark-gray    #unknown
# Yy       =>  clustal-cyan         #large hydrophobic
# Zz       =>  clustal-white        #E or Q
